name: CI/CD for Cocos2D WebGL

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

   

    - name: Install Cocos CLI
      run: |
          git clone https://github.com/cocos2d/cocos2d-console.git
          ls
          npm install
          cd cocos2d-console
          mkdir build
          pyinstaller ./toexec/build_console.py -h -src-path PATH_TO_COCOS_CONSOLE --dst-path OUTPUT_PATH
          cd toexec
          ls
          cocos -v
      env:
        PATH_TO_COCOS_CONSOLE: 'cd cocos2d-console'
        OUTPUT_PATH: 'cd cocos2d-console/build'
          
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: webgl-build
        path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: webgl-build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
