name: CI/CD for Cocos2D WebGL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Cocos CLI
      run: npm install -g cocos-cli

    - name: Install dependencies
      run: npm install

    - name: Build Cocos2D WebGL project
      run: cocos compile -p web

    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: webgl-build
        path: build/web
