name: CI/CD for Cocos2D WebGL

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: dev

    - name : BuildCocos
      uses: miggene/cocos-build@v1.2.3
      with:
        cocos_version: 2.4.7
        
          
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: webgl-build
        path: build/web

    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: webgl-build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
